version: '3'
networks:
  beego-car-rental_network_compose:
    driver: bridge 
services:
  db:
    image: postgres:15.2-alpine
    container_name: beego-car-rental-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database/init/initialize_db.sh:/docker-entrypoint-initdb.d/initialize_db.sh
      - ./database/init/sql:/init/sql
  app:
    container_name: beego-car-rental-app
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      beego-car-rental_network_compose:
    ports:
    - "8080:8080"
volumes:
  db:
    driver: local