version: '3'
networks:
  go-car-rental_network_compose:
    driver: bridge 
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  go-car-rental:
    container_name: go-car-rental
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      go-car-rental_network_compose:
    ports:
    - "8080:8080"
volumes:
  db:
    driver: local