version: '3'
networks:
  beego-car-rental-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
services:
  bee_car_rent_db:
    container_name: beego-car-rental-postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      beego-car-rental-network:
        ipv4_address: 192.168.0.10
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
    volumes: 
      - bee_car_rent_db:/var/lib/postgresql/data
      - ../database/init/initialize_db.sh:/docker-entrypoint-initdb.d/initialize_db.sh
      - ../database/init/sql:/init/sql
  app:
    container_name: beego-car-rental-app
    image: beego-car-rental/server:v1.0.0
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    networks:
      beego-car-rental-network:
    ports:
    - "8080:8080"
volumes:
  bee_car_rent_db:
    driver: local